NTP_MVC/Controllers/HoTroDieuTriController.cs
/*
 * TB Treatment & Supervision Supply System. Copyright (C) 2013 PATH (www.path.org)
 *  
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Author: Tran Trung Hieu
 * Email: htran282@gmail.com / htran@path.org
 * Mobile: +84-0-915164626
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using NTP_MVC.Models;
using System.Web.Services;
using System.Web.Script.Serialization;
using NTP_MVC.Models.VO;
using System.IO;
using Newtonsoft.Json.Linq;
using System.Data.SqlClient;
using System.Data.Entity;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using System.Globalization;
using System.Data;
using NghiepCT.Utilities.Security;
using System.Text;

namespace NTP_MVC.Controllers
{
    public class HoTroDieuTriController : Controller
    {
        NTP_DBEntities db = new NTP_DBEntities();        

        public ActionResult Index()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult DSBenhNhanXN()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult DSBenhNhanNhanTinNhan()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult DSBenhNhanPhanHoiTacDungPhu()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult DSBenhNhanGS()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult ThongKeSMS()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult DMThongDiep()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult DSBenhNhanDoiDiaChi()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        public ActionResult DSBenhNhanTuChoiNhanTinNhan()
        {
            HTDTGS model = new HTDTGS();
            return View(model);
        }

        [WebMethod]
        public string GetProvinces()
        {
            var model = db.DM_Tinh;
            var provinces = model.ToList();
            if (provinces != null && provinces.Count > 0)
            {
                JavaScriptSerializer TheSerializer = new JavaScriptSerializer();
                return TheSerializer.Serialize(provinces);
            }
            else
            {
                return null;
            }
        }

        [WebMethod]
        public string GetDistricts()
        {
            string provinceId = Request.QueryString["provinceId"];
            List<DM_Huyen_Base> districts = (from d in db.DM_Huyen
                                             where d.MA_TINH.Equals(provinceId)
                                             select new DM_Huyen_Base { MA_HUYEN = d.MA_HUYEN, TEN_HUYEN = d.TEN_HUYEN }).ToList();
            if (districts != null && districts.Count > 0)
            {
                JavaScriptSerializer TheSerializer = new JavaScriptSerializer();
                return TheSerializer.Serialize(districts);
            }
            else
            {
                return null;
            }
        }

        [WebMethod]
        public string GetCommunes()
        {
            string districtId = Request.QueryString["districtId"];
            List<DM_Xa> communes = (from c in db.DM_Xa
                                    where c.MA_HUYEN.Equals(districtId)
                                    select c).ToList();
            if (communes != null && communes.Count > 0)
            {
                JavaScriptSerializer TheSerializer = new JavaScriptSerializer();
                return TheSerializer.Serialize(communes);
            }
            else
            {
                return null;
            }
        }

        [WebMethod]
        public string GetTherapies()
        {
            var model = db.DM_PhacDoDT;
            var therapies = model.ToList();
            if (therapies != null && therapies.Count > 0)
            {
                JavaScriptSerializer TheSerializer = new JavaScriptSerializer();
                return TheSerializer.Serialize(therapies);
            }
            else
            {
                return null;
            }
        }

        [WebMethod]
        public string GetLoaiBenhs()
        {
            var model = db.DM_PhanLoaiBenh;
            var loaibenhs = model.ToList();
            if (loaibenhs != null && loaibenhs.Count > 0)
            {
                JavaScriptSerializer TheSerializer = new JavaScriptSerializer();
                return TheSerializer.Serialize(loaibenhs);
            }
            else
            {
                return null;
            }
        }

        [WebMethod]
        public string GetDsBenhNhanXetNghiem()
        {
            string input;
            using (var reader = new StreamReader(Request.InputStream))
            {
                input = reader.ReadToEnd();
            }
            JObject req = JObject.Parse(input);
            BenhNhanGrid grid = GetGridBenhNhanXetNghiem(req, true);
            if (grid != null)
            {
                JavaScriptSerializer TheSerializer = new JavaScriptSerializer();
                return TheSerializer.Serialize(grid);
            }
            else
            {
                return null;
            }
        }

        [WebMethod]
        public string GetBenhNhanTuChoiNhanTinNhan()
        {
            string input;
            using (var reader = new StreamReader(Request.InputStream))
            {
                input = reader.ReadToEnd();
            }
            JObject req = JObject.Parse(input);
            BenhNhanGrid grid = GetGridBenhNhanTuChoiNhanTinNhan(req, true);
            if (grid != null)
            {
                JavaScriptSerializer TheSerializer = new JavaScriptSerializer();
                return TheSerializer.Serialize(grid);
            }
            else
            {
                return null;
            }
        }

        private BenhNhanGrid GetGridBenhNhanTuChoiNhanTinNhan(JObject req, bool isPaging)
        {
            string provinceId = (string)req["provinceId"];
            string districtId = (string)req["districtId"];
            string communeId = (string)req["communeId"];
            int pageSize = (int)req["pageSize"];
            int skip = (int)req["skip"];
            string mobile = (string)req["mobile"];
            string sql = "SELECT count(bn.ID_BenhNhan) FROM dbo.SO_SoDieuTri sdt, dbo.SO_BenhNhan bn "
                    + " WHERE sdt.ID_BENHNHAN=bn.ID_BenhNhan ";
            if (!communeId.Equals("0"))
            {
                sql += " AND bn.MA_XA=@PMAXA ";
            }
            else if (!districtId.Equals("0"))
            {
                sql += " AND bn.MA_HUYEN=@PMAHUYEN ";
            }
            else if (!provinceId.Equals("0"))
            {
                sql += " AND bn.MA_TINH=@PMATINH ";
            }
            sql += " AND (bn.Huy=0 OR bn.Huy IS NULL) AND (sdt.Huy=0 OR sdt.Huy IS NULL) AND sdt.NgayDT IS NOT NULL";
            if (mobile.Length > 0)
            {
                sql += " AND (bn.Sodienthoai like @PMobile OR bn.HoTen like @PHoTen) ";
            }                
            
            List<SqlParameter> parameterList = new List<SqlParameter>();
            if (!communeId.Equals("0"))
            {
                parameterList.Add(new SqlParameter("@PMAXA", communeId));
            }
            else if (!districtId.Equals("0"))
            {
                parameterList.Add(new SqlParameter("@PMAHUYEN", districtId));
            }
            else if (!provinceId.Equals("0"))
            {
                parameterList.Add(new SqlParameter("@PMATINH", provinceId));
            }
            if (mobile.Length > 0)
            {
                mobile = "%" + mobile + "%";
                parameterList.Add(new SqlParameter("@PMobile", mobile));
                parameterList.Add(new SqlParameter("@PHoTen", mobile));
            }
            SqlParameter[] parameters = parameterList.ToArray();
            int total = db.Database.SqlQuery<int>(sql, parameters).Single();

            string sql3 = "SELECT count(DISTINCT(tc.ID_BenhNhan)) "
                    + " FROM dbo.SO_SoDieuTri sdt, dbo.SO_BenhNhan bn, dbo.HTDT_BenhNhanTuChoiNhanTin AS tc "
                    + " WHERE sdt.ID_BENHNHAN=bn.ID_BenhNhan AND tc.ID_BenhNhan=bn.ID_BenhNhan AND tc.TuChoiNhanTinNhanUT=1 ";
            if (!communeId.Equals("0"))
            {
                sql3 += " AND bn.MA_XA=@PMAXA ";
            }
            else if (!districtId.Equals("0"))
            {
                sql3 += " AND bn.MA_HUYEN=@PMAHUYEN ";
            }
            else if (!provinceId.Equals("0"))
            {
                sql3 += " AND bn.MA_TINH=@PMATINH ";
            }
            sql3 += " AND (bn.Huy=0 OR bn.Huy IS NULL) AND (sdt.Huy=0 OR sdt.Huy IS NULL) AND sdt.NgayDT IS NOT NULL ";
            if (mobile.Length > 0)
            {
                sql3 += " AND (bn.Sodienthoai like @PMobile OR bn.HoTen like @PHoTen) ";
            }
            List<SqlParameter> parameterList3 = new List<SqlParameter>();
            if (!communeId.Equals("0"))
            {

NTP_MVC/Views/HoTroDieuTri/DSBenhNhanDoiDiaChi.cshtml
@model NTP_MVC.Models.HTDTGS
 
<script src="@Url.Content("~/Scripts/js/jquery.min.js")"></script>
<link href="@Url.Content("~/Content/styles/lib/bootstrap.min.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/styles/kendo.common.min.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/styles/kendo.default.min.css")" rel="stylesheet">
<link href="@Url.Content("~/Content/styles/style.css")" rel="stylesheet">
<script type="text/javascript" src="@Url.Content("~/Scripts/js/kendo.web.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.confirm/jquery.confirm.js")"></script>
<link href="@Url.Content("~/Scripts/jquery.confirm/jquery.confirm.css")" rel="stylesheet">
<script type="text/javascript" src="@Url.Content("~/Scripts/js/cultures/kendo.culture.vi-VN.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/js/cultures/kendo.culture.vi.min.js")"></script>
@{
    var tmpdistrictId = "0"; var tmpcommuneId = "0";
    if (Session != null && Session["MAHUYEN"] != null && Session["MAHUYEN"] != "")
    {
        tmpdistrictId = (string)Session["MAHUYEN"];
    }
    if (Session != null && Session["MAXA"] != null && Session["MAXA"] != "")
    {
        tmpcommuneId = (string)Session["MAXA"];
    }
}
<script>
    $(document).ready(function () {
        kendo.culture("vi-VN");
        var jsonReq = {};

        dataSourceProvince = new kendo.data.DataSource({
            schema: {
                model: {
                    id: "MA_TINH",
                    fields: {
                        MA_TINH: { editable: false, nullable: true },
                        TEN_TINH: { validation: { required: true } }
                    }
                }
            }
        });

        var filterProvince = $("#filterProvince").kendoDropDownList({
            optionLabel: '---',
            dataTextField: "TEN_TINH",
            dataValueField: "MA_TINH",
            filter: "contains",
            dataSource: dataSourceProvince,
            change: onChangeFilterProvince
        }).data("kendoDropDownList");

        function getProvinces() {
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetProvinces", "HoTroDieuTri")",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    dataSourceProvince.data(data);
                    var provinceId = @Session["MATINH"];
                    if (provinceId != null && provinceId > 0) {
                        filterProvince.value(provinceId);
                        filterProvince.enable(false);
                        onChangeFilterProvince();
                    } else {
                        filterProvince.value('');
                    }
                },
                failure: function (errMsg) {
                    alert(errMsg);
                }
            });
        }

        dataSourceDistrict = new kendo.data.DataSource({
            serverFiltering: true,
            batch: true,
            serverPaging: true,
            schema: {
                model: {
                    id: "MA_HUYEN",
                    fields: {
                        MA_HUYEN: { editable: false, nullable: true },
                        TEN_HUYEN: { validation: { required: true } }
                    }
                }
            }
        });

        var filterDistrict = $("#filterDistrict").kendoDropDownList({
            autoBind: false,
            optionLabel: '---',
            dataTextField: "TEN_HUYEN",
            dataValueField: "MA_HUYEN",
            filter: "contains",
            dataSource: dataSourceDistrict,
            change: onChangeFilterDistrict
        }).data("kendoDropDownList");

        function onChangeFilterProvince() {
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetDistricts", "HoTroDieuTri")",
                data: { provinceId : filterProvince.value() },
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    dataSourceDistrict.data(data);
                    var districtId = @tmpdistrictId;
                    if (districtId != null && districtId != "0") {
                        filterDistrict.value(districtId);
                        filterDistrict.enable(false);
                        onChangeFilterDistrict();
                    } else {
                        filterDistrict.value('');
                    }
                },
                failure: function (errMsg) {
                    alert(errMsg);
                }
            });
        };

        dataSourceCommune = new kendo.data.DataSource({
            serverFiltering: true,
            batch: true,
            serverPaging: true,
            schema: {
                model: {
                    id: "MA_XA",
                    fields: {
                        MA_XA: { editable: false, nullable: true },
                        TEN_XA: { validation: { required: true } }
                    }
                }
            }
        });

        var filterCommune = $("#filterCommune").kendoDropDownList({
            autoBind: false,
            optionLabel: '---',
            dataTextField: "TEN_XA",
            dataValueField: "MA_XA",
            filter: "contains",
            dataSource: dataSourceCommune
        }).data("kendoDropDownList");

        function onChangeFilterDistrict() {
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetCommunes", "HoTroDieuTri")",
                data: { districtId : filterDistrict.value() },
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    dataSourceCommune.data(data);
                    var communeId = @tmpcommuneId;
                    if (communeId != null && communeId != "0") {
                        filterCommune.value(communeId);
                        filterCommune.enable(false);
                    } else {
                        filterCommune.value('');
                    }
                },
                failure: function (errMsg) {
                    alert(errMsg);
                }
            });
        };

        var dataSourceBenhNhanDoiDiaChi = new kendo.data.DataSource({
            pageSize: 10,
            schema: {
                model: {
                    id: "ID_BenhNhan",
                    fields: {
                        ID_BenhNhan: { editable: false, nullable: true },
                        HoTen: { editable: false, validation: { required: true } },
                        Tuoi: { editable: false, validation: { required: true } },
                        Gioitinh: { editable: false, validation: { required: true } },
                        Diachi: { editable: false, validation: { required: true } }
                    }
                }
            },
            serverPaging: true
        });

        var gridBenhNhanDoiDiaChi = $("#gridBenhNhanDoiDiaChi").kendoGrid({
            autoBind: false,
            dataSource: dataSourceBenhNhanDoiDiaChi,
            navigatable: true,
            pageable: true,
            pageable: {
                messages: {
                    display: '{0} - {1} / {2} bệnh nhân',
                    empty: ""
                }
            },
            resizable: true,
            sortable: true,
            columns: [
                { field: "HoTen", title: 'Họ tên', editor: function (element, options) { element.text(options.model.HoTen) }, template: '#= HoTen #' },
                { field: "Tuoi", width: "40px", title: 'Tuổi', editor: function (element, options) { element.text(options.model.Tuoi) }, template: '#= Tuoi #' },
                { field: "Gioitinh", width: "70px", title: 'Giới tính', editor: function (element, options) { element.text(genders[options.model.Gioitinh ? 0 : 1].sex) }, template: "#= Gioitinh ? 'Nam' : 'Nữ' #" },
                { field: "Sodienthoai", title: 'Di động', editor: function (element, options) { element.text(options.model.Sodienthoai) }, template: '#= Sodienthoai #' },
                { field: "TEN_XA", title: 'Phường/Xã', editor: function (element, options) { element.text(options.model.TEN_XA) }, template: "#= TEN_XA #" },
                { field: "NgayTaoBaoCaoDoiDiaChi", width: "90px", title: 'Ngày báo', editor: function (element, options) { var treatDate = options.model.NgayTaoBaoCaoDoiDiaChi; element.text(treatDate ? kendo.toString(kendo.parseDate(treatDate,"yyyy-MM-dd"), "dd/MM/yyyy") : "") }, template: '#= NgayTaoBaoCaoDoiDiaChi ? kendo.toString(kendo.parseDate(NgayTaoBaoCaoDoiDiaChi,"yyyy-MM-dd"), "dd/MM/yyyy") : "" #' },
                {
                    field: "CapNhapDiaChi", width: "130px", title: 'Cập nhập địa chỉ',
                    editor: function (container, options) {
                        var cbChecked = "checked=\"checked\"";
                        if (options.model.CapNhapDiaChi == 1) cbChecked = "";
                        $('<input type="checkbox" class="chkbxDue" id=\"' + options.field + '\" ' + cbChecked + ' />').appendTo(container);

                    },
                    template: '<input type="checkbox" class="chkbxDue" #= CapNhapDiaChi == 1 ? checked="checked" : "" #  />'
                }
            ],
            editable: true,
            dataBound: function (e) {
                if (dataSourceBenhNhanDoiDiaChi.total() > 0)
                    $("#log").html(dataSourceBenhNhanDoiDiaChi.total() + ' bệnh nhân');
                else
                    $("#log").html('Không tìm thấy dữ liệu');
            },
            selectable: true
        }).data("kendoGrid");

        $('#gridBenhNhanDoiDiaChi').on("click", "td", function (e) {
            var selectedTd = $(e.target).closest("td");
            var grdChkBox = selectedTd.find('input:checkbox');
            var dataItem = gridBenhNhanDoiDiaChi.dataItem($(this).closest('tr'));
            if (grdChkBox.prop('checked'))
                dataItem.set('CapNhapDiaChi', 1);
            else
                dataItem.set('CapNhapDiaChi', 0);
        });

        $('#gridBenhNhanDoiDiaChi').on('click', '.chkbxDue', function() {
            var checked = $(this).is(':checked');
            var dataItem = gridBenhNhanDoiDiaChi.dataItem($(this).closest('tr'));
            if (checked)
                dataItem.set('CapNhapDiaChi', 1);
            else
                dataItem.set('CapNhapDiaChi', 0);
        });

        $("#buttonSearch").click(function () {
            searchPatient();

        });

        function searchPatient() {
            var provinceId = $("#filterProvince").val();
            var districtId = $("#filterDistrict").val();
            var communeId = $("#filterCommune").val();

            if (provinceId == '') provinceId = 0;
            if (districtId == '') districtId = 0;
            if (communeId == '') communeId = 0;

            paramDue = {provinceId: provinceId, districtId: districtId, communeId: communeId};
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetDsBenhNhanDoiDiaChi", "HoTroDieuTri")",
                data: JSON.stringify(paramDue),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function(data) {
                    if (data != null) {
                        dataSourceBenhNhanDoiDiaChi.data(data);
                    } else {
                        dataSourceBenhNhanDoiDiaChi.data({});
                    }

                },
                failure: function(errMsg) {
                    alert(errMsg);
                }
            });
        }


        $("#buttonSave").click(function () {

            if (dataSourceBenhNhanDoiDiaChi.total() > 0) {
                $.ajax({
                    url: "@Url.Action("SaveBenhNhanDoiDiaChi", "HoTroDieuTri")",
                    data: JSON.stringify(dataSourceBenhNhanDoiDiaChi.view()),
                    type: 'POST',
                    processData: true,
                    async: false,
                    contentType: "application/json",
                    success: function (data) {
                        alert("Dữ liệu đã được lưu thành công");
                    },
                    failure: function (errMsg) {
                        alert(errMsg);
                    }
                });
            }
        });

        getProvinces();


    });

</script>
<h2>Danh sách bệnh nhân đổi địa chỉ</h2>
Tỉnh:&nbsp;<input id="filterProvince" style="width:130px" />&nbsp;&nbsp;&nbsp;
Huyện:&nbsp;<input id="filterDistrict" style="width:200px" />&nbsp;&nbsp;&nbsp;
Phường / Xã:&nbsp;<input id="filterCommune" style="width:200px" />
<input class="btn btn-primary" style="width:50px;cursor:pointer;" id="buttonSearch" name="buttonSearch" value="Tìm" readonly /><br />
<p style="height:3px"></p>
<font color="#EE7318"><div id="log">&nbsp;</div></font>
<div id="gridBenhNhanDoiDiaChi"></div>
<p style="height:3px"></p>
<input class="btn btn-primary" id="buttonSave" name="buttonSave" value="Lưu" style="width:50px;cursor:pointer;" readonly />