NTP_MVC/Models/BC_ThuNhanBNLao.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_ThuNhanBNLao
    {
        public int ID_BCThunhanBNLao { get; set; }
        public byte Quy { get; set; }
        public int Nam { get; set; }
        public string DVBaocao { get; set; }
        public string NguoiBC { get; set; }
        public Nullable<System.DateTime> NgayBC { get; set; }
        public Nullable<bool> HuyenXN { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public Nullable<bool> PTNhap { get; set; }
        public string MA_TINH { get; set; }
        public string MA_HUYEN { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public Nullable<int> NGUOI_NM { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<System.DateTime> Ngayhuy { get; set; }
    }
}

NTP_MVC/Controllers/BCThuNhanBNLaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using NTP_MVC.Models;
using System.Data.Entity;

namespace NTP_MVC.Controllers
{
    public class BCThuNhanBNLaoController : Controller
    {
        NTP_DBEntities db = new NTP_DBEntities();

        public ActionResult Index()
        {
            Session["MATINH"] = "07";
            Session["MAHUYEN"] = "0703";
            var MaTinh = Session["MATINH"] + "";
            if (MaTinh != "")
            {
                var MaHuyen = Session["MAHUYEN"] + "";
                ViewData["Tinhs"] = db.DM_Tinh.Where(t => t.MA_TINH.Equals(MaTinh)).ToList();
                if (MaHuyen == "")
                {
                    List<DM_Huyen> ListHuyen = new List<DM_Huyen>();
                    DM_Huyen h = new DM_Huyen() { TEN_HUYEN = "-- Tất cả--", MA_HUYEN = "0", MA_TINH = MaTinh };
                    ListHuyen.Add(h);
                    ListHuyen.AddRange(db.DM_Huyen.Where(m => m.MA_TINH.Equals(MaTinh)).ToList());
                    ViewData["Huyens"] = ListHuyen;
                }
                else
                {
                    ViewData["Huyens"] = db.DM_Huyen.Where(b => b.MA_HUYEN.Equals(MaHuyen)).ToList();
                }
                GetListBCThuNhanBNLao();
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [ValidateInput(false)]
        public ActionResult GridBCThuNhanBNLao()
        {

            GetListBCThuNhanBNLao();
            return PartialView("GridBCThuNhanBNLao");
        }

        private void GetListBCThuNhanBNLao()
        {
            string matinh = Session["MATINH"] + "";

            int MaQuy = Request.Params["MaQuy"] != null ? Convert.ToInt16(Request.Params["MaQuy"]) : 0;
            int Nam = Request.Params["Nam"] != null ? Convert.ToInt32(Request.Params["Nam"]) : 0;

            ViewData["ListBCThuNhanBNLao"] = (from d in db.BC_ThuNhanBNLao
                                              where d.MA_TINH.Equals(matinh)
                                                  && d.Quy == MaQuy
                                                  && d.Nam == Nam
                                              select d).ToList();
        }

        [ValidateInput(false)]
        public ActionResult Edit()
        {

            int id = Request.Params["id"] != null ? Convert.ToInt32(Request.Params["id"]) : 0;
            if (id != 0)
            {
                var BCThuNhan = db.BC_ThuNhanBNLao.Where(a => a.ID_BCThunhanBNLao == id).FirstOrDefault();
                var MaTinh = BCThuNhan.MA_TINH;
                var MaHuyen = BCThuNhan.MA_HUYEN;
                ViewData["Tinhs"] = db.DM_Tinh.Where(t => t.MA_TINH.Equals(BCThuNhan.MA_TINH)).ToList();
                if (BCThuNhan.MA_HUYEN != null && BCThuNhan.MA_HUYEN != "")
                {
                    List<DM_Huyen> ListHuyen = new List<DM_Huyen>();
                    DM_Huyen h = new DM_Huyen() { TEN_HUYEN = "", MA_HUYEN = "", MA_TINH = MaTinh };
                    ListHuyen.Add(h);
                    ListHuyen.AddRange(db.DM_Huyen.Where(m => m.MA_TINH.Equals(MaTinh)).ToList());
                    ViewData["Huyens"] = ListHuyen;
                }
                else
                {
                    ViewData["Huyens"] = db.DM_Huyen.Where(b => b.MA_HUYEN.Equals(MaHuyen)).ToList();
                }
                return View("EditBCThuNhanBNLao", BCThuNhan);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost, ValidateInput(false)]

        public ActionResult Edit([ModelBinder(typeof(DevExpressEditorsBinder))] BC_ThuNhanBNLao bctn)
        {
            return null;
        }


        public ActionResult GridBCThuNhanBNLao1()
        {
            var MaTinh = Session["MATINH"] + "";
            if (Request.Params["MaHuyen"] != null)
            {
                var MaHuyen = Session["MAHUYEN"] + "";
                int id = Request.Params["id"] != null ? Convert.ToInt32(Request.Params["id"]) : 0;

                string nguoibaocao = Request.Params["NguoiBaoCao"] + "";
                DateTime ngaybaocao = Request.Params["NgayBaoCao"] != "" ? Convert.ToDateTime(Request.Params["NgayBaoCao"]) : DateTime.MinValue;

                int MaQuy = Request.Params["MaQuy"] != null ? Convert.ToInt16(Request.Params["MaQuy"]) : 0;
                int Nam = Request.Params["Nam"] != null ? Convert.ToInt32(Request.Params["Nam"]) : 0;

                var id_BCThuNhanNBLao = (from d in db.BC_ThuNhanBNLao
                                         where d.MA_TINH.Equals(MaTinh)
                                             && d.MA_HUYEN.Equals(MaHuyen)
                                             && d.Quy == MaQuy
                                             && d.Nam == Nam
                                         select d.ID_BCThunhanBNLao).SingleOrDefault();
                if (id_BCThuNhanNBLao != 0)
                {
                    ViewData["ListBCThuNhanBNLao1"] = (from d in db.BC_ThuNhanBNLao1
                                                       where d.ID_BCThunhanBNLao == id_BCThuNhanNBLao
                                                       select d).ToList();
                }
                else
                {
                    BC_ThuNhanBNLao item = new BC_ThuNhanBNLao();
                    item.MA_TINH = MaTinh;
                    item.MA_HUYEN = MaHuyen;
                    item.Nam = Nam;
                    item.Quy = (byte)MaQuy;
                    if (ngaybaocao != DateTime.MinValue)
                    {
                        item.NgayBC = ngaybaocao;
                    }

                    item.NguoiBC = nguoibaocao;
                    item.DVBaocao = MaHuyen;
                    db.BC_ThuNhanBNLao.Add(item);
                    db.SaveChanges();

                    for (int i = 0; i < 3; i++)
                    {
                        BC_ThuNhanBNLao1 subitem = new BC_ThuNhanBNLao1();
                        subitem.ID_BCThunhanBNLao = item.ID_BCThunhanBNLao;
                        subitem.Phanloai = i;
                        db.BC_ThuNhanBNLao1.Add(subitem);
                    }
                    db.SaveChanges();
                    ViewData["ListBCThuNhanBNLao1"] = (from d in db.BC_ThuNhanBNLao1
                                                       where d.ID_BCThunhanBNLao.Equals(item.ID_BCThunhanBNLao)
                                                       select d).ToList();

                }
            }
            return PartialView("GridBCThuNhanBNLao1");
        }

        [ValidateInput(false)]
        public ActionResult GridBCThuNhanBNLao1BatchEditingUpdateModel(MVCxGridViewBatchUpdateValues<BC_ThuNhanBNLao1, int> updateValues)
        {
            foreach (var item in updateValues.Update)
            {
                if (updateValues.IsValid(item))
                    UpdateBCThuNhanBNLao1(item, updateValues);
            }
            return GridBCThuNhanBNLao1();
        }
        protected void UpdateBCThuNhanBNLao1(BC_ThuNhanBNLao1 item, MVCxGridViewBatchUpdateValues<BC_ThuNhanBNLao1, int> updateValues)
        {
            try
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception e)
            {
                updateValues.SetErrorText(item, e.Message);
            }
        }


        [HttpPost, ValidateInput(false)]
        public ActionResult GridBCThuNhanBNLao1AddNew(BC_ThuNhanBNLao1 item)
        {
            var model = db.BC_ThuNhanBNLao1;
            if (ModelState.IsValid)
            {
                try
                {
                    db.BC_ThuNhanBNLao1.Add(item);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("GridBCThuNhanBNLao1", model.ToList());
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult GridBCThuNhanBNLao1Update(BC_ThuNhanBNLao1 item)
        {
            var model = db.BC_ThuNhanBNLao1;
            if (ModelState.IsValid)
            {
                try
                {
                    var modelItem = model.FirstOrDefault(it => it.ID_BCThunhanBNLao == item.ID_BCThunhanBNLao);
                    if (modelItem != null)
                    {
                        UpdateModel(modelItem);
                        db.SaveChanges();
                    }
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("GridBCThuNhanBNLao1", model.ToList());
        }


        public ActionResult GridBCThuNhanBNLao2()
        {
            //var MaTinh = "65";// Session["MATINH"] + "";  
            var MaTinh = Session["MATINH"] + "";
            if (Request.Params["MaHuyen"] != null)
            {

                //var MaHuyen = Request.Params["MaHuyen"] + "";// Session["MAHUYEN"] + "";
                var MaHuyen = Session["MAHUYEN"] + "";
                int id = Request.Params["id"] != null ? Convert.ToInt32(Request.Params["id"]) : 0;

                string nguoibaocao = Request.Params["NguoiBaoCao"] + "";
                DateTime ngaybaocao = Request.Params["NgayBaoCao"] != "" ? Convert.ToDateTime(Request.Params["NgayBaoCao"]) : DateTime.MinValue;

                int MaQuy = Request.Params["MaQuy"] != null ? Convert.ToInt16(Request.Params["MaQuy"]) : 0;

NTP_MVC/Views/BCThuNhanBNLao/EditBCTN.cshtml
@Html.DevExpress().FormLayout(settings =>
        {
            settings.Name = "EditBCThuNhanBNLao";
            settings.RequiredMarkDisplayMode = RequiredMarkMode.None;
            settings.Width = Unit.Percentage(100);


            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 1. Toàn bộ bệnh nhân lao đăng ký điều trị trong quý (trừ bệnh nhân chuyển  đến ) và tình trạng HIV, lao trẻ em";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {

                    Html.RenderPartial("GridBCTN1");
                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 2. Bệnh nhân lao phổi AFB dương tính mới theo tuổi, giới";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCTN2");

                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 3. Toàn bộ bệnh nhân lao đăng ký điều trị trong quý (trừ bệnh nhân chuyển đến) với sự tham gia đóng góp của Y tế công, tư trong giám sát hỗ trợ điều trị bệnh nhân lao";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCTN3");

                });
            });
        }).GetHtml()

NTP_MVC/Views/BCThuNhanBNLao/EditBCThuNhanBNLao_Old.cshtml
@model NTP_MVC.Models.BC_ThuNhanBNLao

<script>
    $(function () {
        GridBCTN1.PerformCallback();
        // GridBCTN2.PerformCallback();
        // GridBCTN2.PerformCallback();
    });
    var currentColumnName;
    function OnBatchEditStartEditing(s, e) {
        currentColumnName = e.focusedColumn.fieldName;
    };

    function OnBatchEditEndEditing(s, e) {
        window.setTimeout(function () {
            var a1 = s.batchEditApi.GetCellValue(e.visibleIndex, "Moi");
            var a2 = s.batchEditApi.GetCellValue(e.visibleIndex, "Taiphat");
            var a3 = s.batchEditApi.GetCellValue(e.visibleIndex, "Thatbai");
            var a4 = s.batchEditApi.GetCellValue(e.visibleIndex, "Taitri");
            var a5 = s.batchEditApi.GetCellValue(e.visibleIndex, "AFBKhac");
            var a6 = s.batchEditApi.GetCellValue(e.visibleIndex, "AmNho");
            var a7 = s.batchEditApi.GetCellValue(e.visibleIndex, "AmTrung");
            var a8 = s.batchEditApi.GetCellValue(e.visibleIndex, "AmLon");
            var a9 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiPhoiNho");
            var a10 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiPhoiTrung");
            var a11 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiPhoiLon");
            var a12 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiphoiKhac");
            s.batchEditApi.SetCellValue(e.visibleIndex, "TongCong", a1 + a2 + a3 + a4 + a5 + a6 + a7 + a8 + a9 + a10 + a11 + a12);
        }, 10);
    };
</script>

@using (Html.BeginForm("Edit", "BCThuNhanBNLao" ))
{
    @Html.DevExpress().FormLayout(settings =>
        {
            settings.Name = "EditBCThuNhanBNLao";
            settings.RequiredMarkDisplayMode = RequiredMarkMode.None;
            settings.Width = Unit.Percentage(100);
            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Chỉnh sửa báo cáo tình hình thu nhận bệnh nhân lao";
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(item =>
                {
                    item.Caption = "Thuộc đơn vị";
                    item.ShowCaption = DefaultBoolean.False;
                    item.SetNestedContent(() =>
                    {
                        ViewContext.Writer.Write("<table><tr><td style=\"padding-right:5px;\">");
                        Html.RenderPartial("_ComboBoxTinh");
                        ViewContext.Writer.Write("</td><td>");
                        Html.DevExpress().ComboBoxFor(i => i.MA_HUYEN, mySettings =>
                       {
                           mySettings.Name = "MA_HUYEN";
                           mySettings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
                           mySettings.Properties.DropDownStyle = DropDownStyle.DropDown;
                           mySettings.Properties.CallbackPageSize = 5000;
                           mySettings.Properties.ValueField = "MA_HUYEN";
                           mySettings.Properties.TextField = "TEN_HUYEN";
                           mySettings.Properties.ValueType = typeof(string);
                           mySettings.Properties.Caption = "Huyện";
                       }).BindList(ViewData["Huyens"]).GetHtml();
                        // Html.RenderPartial("_ComboBoxHuyen");
                        ViewContext.Writer.Write("</td><td style='padding-left:30px;padding-right:5px;'>");
                        Html.DevExpress().ComboBoxFor(i => i.Quy, mySettings =>
                        {
                            mySettings.Name = "Quy";
                            mySettings.Properties.Caption = "Năm BC";
                            mySettings.Width = Unit.Pixel(100);
                            mySettings.Properties.Items.Add("Quý I", (byte)1);
                            mySettings.Properties.Items.Add("Quý II", (byte)2);
                            mySettings.Properties.Items.Add("Quý III", (byte)3);
                            mySettings.Properties.Items.Add("Quý IV", (byte)4);
                        }).GetHtml();

                        ViewContext.Writer.Write("</td><td style='padding-right:5px;'>");
                        Html.DevExpress().TextBoxFor(i => i.Nam, mySettings =>
                        {
                            mySettings.Name = "Nam";
                            mySettings.Properties.Caption = "";
                            mySettings.Properties.CaptionSettings.ShowColon = false;
                            mySettings.Width = Unit.Pixel(60);
                        }).GetHtml();

                        ViewContext.Writer.Write("</td><td style='padding-right:5px;'>");
                        Html.DevExpress().DateEditFor(i => i.NgayBC, mySettings =>
                        {
                            mySettings.Name = "NgayBC";
                            mySettings.Properties.Caption = "Ngày báo cáo";
                            mySettings.Width = Unit.Pixel(100);
                        }).GetHtml();

                        ViewContext.Writer.Write("</td><td style='padding-right:5px;'>"); 
                        Html.DevExpress().TextBoxFor(i => i.NguoiBC, mySettings =>
                        {
                            mySettings.Name = "NguoiBC";
                            mySettings.Properties.Caption = "Người báo cáo";
                            mySettings.Width = Unit.Pixel(100);
                        }).GetHtml();

                        ViewContext.Writer.Write("</td><td style='padding-left:20px;padding-right:5px;'>");
                        Html.DevExpress().Button(
                                    MyButton =>
                                    {
                                        MyButton.Name = "btnSearch";
                                        MyButton.Width = 90;
                                        MyButton.Text = "Xem";
                                        MyButton.ClientSideEvents.Click = "function() { GridBCTN1.PerformCallback(); }";
                                        MyButton.Images.Image.Url = "~/Content/Images/search.png";
                                        MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                                    }).Render();

                        //button them
                        ViewContext.Writer.Write("</td><td style='padding-left:20px;padding-right:5px;'>");
                        Html.DevExpress().Button(
                                    MyButton =>
                                    {
                                        MyButton.Name = "btnThem";
                                        MyButton.Width = 90;
                                        MyButton.Text = "Thêm báo cáo";
                                        MyButton.ClientSideEvents.Click = "function() { alert('Đang xây dựng'); }";
                                        MyButton.Images.Image.Url = "~/Content/Images/add.png";
                                        MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                                    }).Render();

                        //button luu
                        ViewContext.Writer.Write("</td><td style='padding-left:20px;padding-right:5px;'>");
                        Html.DevExpress().Button(
                                    MyButton =>
                                    {
                                        MyButton.Name = "btnluu";
                                        MyButton.Width = 90;
                                        MyButton.Text = "Lưu báo cáo";
                                        MyButton.ClientSideEvents.Click = "function() { GridBCTN1.UpdateEdit(); }";
                                        MyButton.Images.Image.Url = "~/Content/Images/save.png";
                                        MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                                        MyButton.UseSubmitBehavior = true;
                                    }).Render();
                        //button xoa
                        ViewContext.Writer.Write("</td><td style='padding-left:20px;padding-right:5px;'>");
                        Html.DevExpress().Button(
                                    MyButton =>
                                    {
                                        MyButton.Name = "btnXoa1";
                                        MyButton.Width = 90;
                                        MyButton.Text = "(Hủy) nhập lại";
                                        MyButton.ClientSideEvents.Click = "function() { GridBCTN1.CancelEdit(); }";
                                        MyButton.Images.Image.Url = "~/Content/Images/cancel.png";
                                        MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                                    }).Render();
                        ViewContext.Writer.Write("</td></tr></table>");
                        Html.HiddenFor(i => i.ID_BCThunhanBNLao);
                    });
                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 1: Toàn bộ bệnh nhân Lao và Lao/HIV đăng ký điều trị trong quý";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {

                    Html.RenderPartial("GridBCTN1");
                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 2: Bệnh nhân lao phổi AFB dương tính mới theo tuổi, giới";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCTN2");

                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 3: Toàn bộ bệnh nhân lao đăng ký điều trị trong quý (trừ bệnh nhân chuyển đến) với sự tham gia đóng góp của Y tế công, tư trong giám sát hỗ trợ điều trị bệnh nhân lao";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCTN2");

                });
            });
        }).GetHtml();
}

NTP_MVC/Views/BCThuNhanBNLao/GridBCThuNhanBNLao.cshtml
@model NTP_MVC.Models.BCThuNhanModel
@using DevExpress.Web.Rendering
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        /*Initial*/
        settings.Name = "GridBCThuNhanBNLao";
        settings.Width = Unit.Percentage(100);
        settings.CallbackRouteValues = new { Controller = "BCThuNhanBNLao", Action = "GridBCThuNhanBNLao" };
        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "BCThuNhanBNLao", Action = "BC_TNBNLAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "BCThuNhanBNLao", Action = "BC_TNBNLUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "BCThuNhanBNLao", Action = "BC_TNBNLDelete" };
        settings.ClientSideEvents.BeginCallback = "function(s, e) { e.customArgs['MaQuy'] =cboQuy.GetValue(); e.customArgs['Nam'] =txtNam.GetText(); }";

        /* Behavior */
        settings.SettingsBehavior.AllowSelectSingleRowOnly = true;
        settings.SettingsBehavior.AllowFocusedRow = true;
        settings.SettingsBehavior.ConfirmDelete = true;
        settings.SettingsBehavior.AllowDragDrop = false;


        /*Events*/
        settings.SettingsEditing.Mode = GridViewEditingMode.Inline;
        settings.SettingsEditing.BatchEditSettings.EditMode = GridViewBatchEditMode.Row;

        settings.ClientSideEvents.FocusedRowChanged = "OnGridBCThuNhanBNLaoFocusedRowChanged";
        settings.ClientSideEvents.RowDblClick = "OnGridBCThuNhanBNLaoRowDblClick";

        /* Pager */
        settings.SettingsPager.Mode = GridViewPagerMode.ShowPager;
        settings.SettingsPager.AllButton.Text = "Tất cả";
        settings.SettingsPager.NextPageButton.Text = "Tiếp theo >";
        settings.SettingsPager.PrevPageButton.Text = "< Quay lại";
        settings.SettingsPager.Visible = true;

        settings.KeyFieldName = "ID_BCThunhanBNLao";

        //settings.Columns.Add(i =>
        //{
        //    i.FieldName = "Quy";
        //    i.Caption = "Quý";
        //    i.Width = Unit.Pixel(250);
        //    i.HeaderStyle.Paddings.Padding = Unit.Pixel(2);
        //});
        //settings.Columns.Add(i =>
        //{
        //    i.FieldName = "Nam";
        //    i.Caption = "Năm";
        //    i.Width = Unit.Pixel(300);
        //    i.HeaderStyle.Paddings.Padding = Unit.Pixel(2);
        //});
        settings.Columns.Add(i =>
        {
            i.FieldName = "NgayBC";
            i.Caption = "Ngày báo cáo";
            i.Width = Unit.Percentage(30);
            i.HeaderStyle.Paddings.Padding = Unit.Pixel(2);
            i.ColumnType = MVCxGridViewColumnType.DateEdit;
        });
        settings.Columns.Add(i =>
        {
            i.FieldName = "NguoiBC";
            i.Caption = "Người báo cáo";
            i.Width = Unit.Percentage(30);
            i.HeaderStyle.Paddings.Padding = Unit.Pixel(2);
        });
        settings.Columns.Add(i =>
        {
            i.FieldName = "DVBaocao";
            i.Caption = "Cơ sở y tế";
            i.Width = Unit.Percentage(60);
            i.HeaderStyle.Paddings.Padding = Unit.Pixel(2);
            i.ColumnType = MVCxGridViewColumnType.ComboBox;
            var comboBoxProperties = i.PropertiesEdit as ComboBoxProperties;
            comboBoxProperties.TextField = "TEN_HUYEN";
            comboBoxProperties.ValueField = "MA_HUYEN";
            comboBoxProperties.DataSource = Model == null ? null : Model.ListHuyen;
            comboBoxProperties.ValueType = typeof(string);
            comboBoxProperties.EnableSynchronization = DefaultBoolean.False;
            comboBoxProperties.IncrementalFilteringMode = IncrementalFilteringMode.StartsWith;
        });


    }).Bind(Model.BC_ThuNhanBNLao).GetHtml();
}