NTP_MVC/Controllers/SoDieuTriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using NTP_MVC.Models;
using System.Data.Entity;

namespace NTP_MVC.Controllers
{
    public class SoDieuTriController : Controller
    {
        // GET: SoDieuTri
        public ActionResult Index()
        {
            var MaTinh = Session["MATINH"] + "";
            if (MaTinh != "")
            {
                var MaHuyen = Session["MAHUYEN"] + "";
                ViewData["Tinhs"] = db.DM_Tinh.Where(t => t.MA_TINH.Equals(MaTinh)).ToList();
                ViewData["Huyens"] = db.DM_Huyen.Where(t => t.MA_HUYEN.Equals(MaHuyen)).ToList();

                SoDieuTriModel model = new SoDieuTriModel();
                model.ListBN = db.SO_BenhNhan.Where(b => b.MA_HUYEN == MaHuyen).ToList();
                model.ListSDT = new List<SO_SoDieuTri>();

                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        NTP_DBEntities db = new NTP_DBEntities();

        [ValidateInput(false)]
        public ActionResult GridSoDieuTriList()
        {
            GetSoDieuTriCuaBenhNhan();
            return PartialView("_GridSoDieuTri", ViewData["ListSoDieuTri"]);
        }

        public ActionResult Edit()
        {
            var MaTinh = Session["MATINH"] + "";
            if (MaTinh != "")
            {
                long ID_BenhNhan = 0;
                long ID_SoDieuTri = 0;
                if (Request.Params["ID_BenhNhan"] != "" && Request.Params["ID_BenhNhan"] != "null")
                {
                    ID_BenhNhan = Convert.ToInt64(Request.Params["ID_BenhNhan"]);
                }

                if (Request.Params["ID_SoDieuTri"] != "" && Request.Params["ID_SoDieuTri"] != "null")
                {
                    ID_SoDieuTri = Convert.ToInt64(Request.Params["ID_SoDieuTri"]);
                }

                SoDieuTriModel model = new SoDieuTriModel();

                model.BN = db.SO_BenhNhan.Where(b => b.ID_BenhNhan == ID_BenhNhan).SingleOrDefault();
                model.BN.ID_BenhNhan = ID_BenhNhan;
                model.SDT = db.SO_SoDieuTri.Where(b => b.ID_SoDieuTri == ID_SoDieuTri).SingleOrDefault();

                if (model.BN == null)
                {
                    model.BN = new SO_BenhNhan();
                }
                if (model.SDT == null)
                {
                    model.SDT = new SO_SoDieuTri();
                }

                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }



        [HttpPost, ValidateInput(false)]
        public string Edit(SO_BenhNhan bn, SO_SoDieuTri sdt)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    bn.MA_HUYEN = Session["MAHUYEN"] + "";
                    bn.MA_TINH = Session["MATINH"] + "";
                    bn.ID_BenhNhan = Request.Params["ID_BenhNhan"] + "" != "" ? Convert.ToInt64(Request.Params["ID_BenhNhan"].Split(',')[0]) : 0;
                    sdt.ID_SoDieuTri = Request.Params["ID_SoDieuTri"] + "" != "" ? Convert.ToInt64(Request.Params["ID_SoDieuTri"]) : 0;
                    if (bn.ID_BenhNhan != 0)
                    {
                        bn.Ngay_SD = DateTime.Now;
                        db.SO_BenhNhan.Attach(bn);
                        db.Entry(bn).State = EntityState.Modified;
                        db.SaveChanges();
                        sdt.ID_BENHNHAN = bn.ID_BenhNhan;
                        if (sdt.ID_SoDieuTri != 0)
                        {
                            sdt.Ngay_SD = DateTime.Now;
                            db.SO_SoDieuTri.Attach(sdt);
                            db.Entry(sdt).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        else
                        {
                            sdt.NGAY_NM = DateTime.Now;
                            db.SO_SoDieuTri.Add(sdt);
                            db.SaveChanges();
                        }
                    }
                    else
                    {
                        bn.NGAY_NM = DateTime.Now;
                        db.SO_BenhNhan.Add(bn);
                        db.SaveChanges();

                        sdt.ID_BENHNHAN = bn.ID_BenhNhan;
                        db.SO_SoDieuTri.Add(sdt);
                        db.SaveChanges();
                    }
                    return "Cập nhật thành công";
                }
                catch (Exception e)
                {
                    return "Cập nhật thất bại, lỗi:" + e.Message;
                }
            }
            else
                return "Có lỗi khi nhập dữ liệu, hãy kiểm tra và thử lại";
        }

        public void GetSoDieuTriCuaBenhNhan()
        {
            var s = Request.Params["ID_BenhNhan"] + "";
            if (s != "")
            {
                ViewData["ListSoDieuTri"] = db.SO_SoDieuTri.Where(bn => bn.ID_BENHNHAN.ToString().Contains(s)).ToList();
            }
            ViewData["ListHuyen"] = db.DM_Huyen.ToList();
        }


        [ValidateInput(false)]
        public ActionResult GridSoDieuTri()
        {
            var model = db.SO_SoDieuTri;
            return PartialView("_GridSoDieuTri", model.ToList());
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult GridSoDieuTriAddNew(SO_SoDieuTri item)
        {
            var model = db.SO_SoDieuTri;
            if (ModelState.IsValid)
            {
                try
                {
                    model.Add(item);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            GetSoDieuTriCuaBenhNhan();
            return PartialView("_GridSoDieuTri", ViewData["ListSoDieuTri"]);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridSoDieuTriUpdate(SO_SoDieuTri item)
        {
            var model = db.SO_SoDieuTri;
            if (ModelState.IsValid)
            {
                try
                {
                    var modelItem = model.FirstOrDefault(it => it.ID_SoDieuTri == item.ID_SoDieuTri);
                    if (modelItem != null)
                    {
                        UpdateModel(modelItem);
                        db.SaveChanges();
                    }
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            GetSoDieuTriCuaBenhNhan();
            return PartialView("_GridSoDieuTri", ViewData["ListSoDieuTri"]);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridSoDieuTriDelete(Int64 ID_SoDieuTri)
        {
            var model = db.SO_SoDieuTri;
            if (ID_SoDieuTri >= 0)
            {
                try
                {
                    var item = model.FirstOrDefault(it => it.ID_SoDieuTri == ID_SoDieuTri);
                    if (item != null)
                        model.Remove(item);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            GetSoDieuTriCuaBenhNhan();
            return PartialView("_GridSoDieuTri", ViewData["ListSoDieuTri"]);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SearchBenhNhan(string matinh, string mahuyen, string hoten, string mabnql, string socmnd, DateTime? nkbfrom, DateTime? nkbto)
        {
            List<SO_BenhNhan> ListBN = (from d in db.SO_BenhNhan
                                        where (mahuyen != "" ? d.MA_HUYEN.Equals(mahuyen) : true
                                     && d.MA_TINH.Equals(matinh))
                                     && ((hoten != "" ? d.HoTen.Contains(hoten) : true)
                                     && (mabnql != "" ? d.MaBNQL.Contains(mabnql) : true)
                                     && (socmnd != "" ? d.SoCMND.Contains(socmnd) : true))
                                        select d).ToList();

            if (nkbfrom != null || nkbto != null)
            {

                List<long> ListID_BN = ListBN.Select(a => a.ID_BenhNhan).ToList();
                List<long> ListID_SKB = (from d in db.SO_SoKhamBenh
                                         where
                                        ListID_BN.Contains(d.ID_BENHNHAN)
                                      && (nkbfrom != null ? d.NgayKhamBenh >= nkbfrom : true)
                                      && (nkbto != null ? d.NgayKhamBenh <= nkbto : true)
                                         select d.ID_BENHNHAN).ToList();
                ListBN = ListBN.Where(a => ListID_SKB.Contains(a.ID_BenhNhan)).ToList();
            }
            return PartialView("_GridBenhNhan", ListBN);
        }

        public ActionResult DocumentViewerPartial()
        {
            Reports.DanhSachBenhNhanPrint report = new Reports.DanhSachBenhNhanPrint();
            NTP_DBEntities db = new NTP_DBEntities();
            var MaTinh = Session["MATINH"] + "";

            var MaHuyen = Session["MAHUYEN"] + "";
            report.DataSource = (from a in db.InDanhSachBenhNhans
                                 where a.MA_TINH.Equals(MaTinh)
                                      && (MaHuyen != "" ? a.MA_HUYEN.Equals(MaHuyen) : true)
                                 select a).Take(100).ToList();

NTP_MVC/Views/SoDieuTri/Edit.cshtml
@model NTP_MVC.Models.SoDieuTriModel

<script>

    function OnGridPXNFocusedRowChanged(s, e) {
        if (s.GetFocusedRowIndex() != -1) {
            ID_PhieuXetNghiem = s.GetRowKey(s.GetFocusedRowIndex());
            GridKetQuaXetNghiem.PerformCallback();
        }
    }

    function GridKQPXN_OnBeginCallback(s, e) {
        e.customArgs["ID_PhieuXetNghiem"] = ID_PhieuXetNghiem;
    }
    function OnGridPXNRowDblClick(s, e) {
        s.StartEditRow(s.GetFocusedRowIndex());
    }
    function OnGridKQXNRowDblClick(s, e) {
        s.StartEditRow(s.GetFocusedRowIndex());
    }

    function OnGridPXNInit(s, e) {
        s.SetFocusedRowIndex(-1);
    }
</script>


@using (Ajax.BeginForm("Edit", "SoDieuTri",
                                    new { ID_BenhNhan = Model.BN.ID_BenhNhan, ID_SoDieuTri = Model.SDT.ID_SoDieuTri },
                                    new AjaxOptions
                                    {
                                        HttpMethod = "POST",
                                        UpdateTargetId = "MsgError",
                                        InsertionMode = InsertionMode.Replace
                                    }))
{
    <h2 style="text-align: center; width:100%;">
        Cập nhật thông tin bệnh nhân
    </h2> Html.RenderPartial("_FormBenhNhan", Model.BN);
    <h2 style="text-align: center; width:100%;">
        Thông tin Sổ Khám Bệnh của bệnh nhân
    </h2>
    Html.RenderPartial("_FormSoDieuTri", Model.SDT);

    <div style='float:right'>
        @Html.DevExpress().Button(
        btnSettings =>
        {
            btnSettings.Name = "btnUpdate1";
            btnSettings.Text = "Lưu toàn bộ";
            btnSettings.Height = 30;
            btnSettings.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
            btnSettings.Images.Image.Url = "~/Content/Images/save.png";
            btnSettings.UseSubmitBehavior = true;
        }).GetHtml()
        @Html.DevExpress().Button(
        btnSettings =>
        {
            btnSettings.Name = "btnCancel1";
            btnSettings.Text = "Đóng màn hình";
            btnSettings.Height = 30;
            btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
            btnSettings.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
            btnSettings.Images.Image.Url = "~/Content/Images/cancel.png";
            btnSettings.ClientSideEvents.Click = "function(s, e){ document.location ='" + DevExpressHelper.GetUrl(
                                                                        new { Controller = "SoDieuTri", Action = "Index" }) + "' }";
        }).GetHtml()
    </div>
    <div id="MsgError" style='margin-right:50px; float:right; font-size:14px; font-weight:bold; color:blue'>
    </div>
}

@Html.DevExpress().PopupControl(
        settings =>
        {
            settings.Name = "BaoCaoPopupControl";
            settings.PopupElementID = "popupArea";
            settings.LoadContentViaCallback = LoadContentViaCallback.OnFirstShow;
            settings.CallbackRouteValues = new { Controller = "PhieuXetNghiem", Action = "DocumentViewerPartial" };
            // settings.ClientSideEvents.CallbackError = "function(s, e ) { alert(e.message); }";


            settings.HeaderText = "XEM BÁO CÁO";
            settings.AllowDragging = true;
            settings.AllowResize = true;
            settings.CloseAction = CloseAction.CloseButton;

            settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
            settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;

            settings.Height = 700;
            settings.Width = 700;
        }).GetHtml()

NTP_MVC/Views/SoDieuTri/_ComboSearchBenhNhan.cshtml
@Html.DevExpress().ComboBox(settings =>
{
    settings.Name = "SearchCombobox";
    settings.Properties.Caption = "Nhập thông tin tìm kiếm bệnh nhân";
    settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
    settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
    settings.Properties.DropDownStyle = DropDownStyle.DropDown;
    settings.Properties.DropDownHeight = 350;
    settings.Width = Unit.Pixel(210);

    settings.CallbackRouteValues = new { Controller = "BenhNhan", Action = "ComboSearchBenhNhan" };
    settings.Properties.CallbackPageSize = 20;
    settings.Properties.ValueField = "ID_BenhNhan";
    settings.Properties.TextField = "HoTen";
    settings.Properties.FilterMinLength = 4;
   // settings.Properties.ValueType = typeof(long); 
    settings.Properties.TextFormatString = "{0} {1} {2} {3} {4} {5} {6}";
    settings.Properties.ClientSideEvents.BeginCallback = "function(s, e) { e.customArgs['SearchCombobox'] = SearchCombobox.GetValue(); }";

    settings.Properties.Columns.Add("HoTen", "Họ và Tên", 130);
    settings.Properties.Columns.Add("Gioitinh", "Giới tính", 60);
    settings.Properties.Columns.Add("Tuoi", "Tuổi", 40);
    settings.Properties.Columns.Add("SoCMND", "Số Chứng Minh Thư", 120);
    settings.Properties.Columns.Add("MaBNQL", "Mã Bệnh Nhân", 120);
    settings.Properties.Columns.Add("TenTinh", "Tỉnh", 100);
    settings.Properties.Columns.Add("TenHuyen", "Huyện", 250);
    settings.Properties.ClientSideEvents.SelectedIndexChanged = "RedirectToBenhNhanID";
}).BindList(ViewData["BenhNhan"]).GetHtml()

NTP_MVC/Views/SoDieuTri/_DocumentViewerPartial.cshtml
@Html.DevExpress().DocumentViewer(settings =>
{
    settings.Name = "DocumentViewer";
    settings.Width = Unit.Percentage(100);
    settings.Height = Unit.Percentage(90);
    settings.CallbackRouteValues = new
    {
        Controller = "SoKhamBenh",
        Action = "DocumentViewerPartial"
    };
    settings.ExportRouteValues = new
    {
        Controller = "SoKhamBenh",
        Action = "DocumentViewerExport"
    };
    settings.Report = (XtraReport)Model;
}).GetHtml()

NTP_MVC/Views/SoDieuTri/_FormBenhNhan.cshtml
@model NTP_MVC.Models.SO_BenhNhan

@Html.DevExpress().FormLayout(settings =>
{
    settings.Name = "BenhNhanFormLayout";
    settings.Width = Unit.Percentage(100);
    settings.ColCount = 4;
    var groupItem = settings.Items.AddGroupItem(groupSettings =>
    {
        groupSettings.Caption = "Thông tin bệnh nhân";
        groupSettings.ShowCaption = DefaultBoolean.True;
        groupSettings.GroupBoxDecoration = GroupBoxDecoration.Box;
        groupSettings.CellStyle.Paddings.Padding = Unit.Pixel(0);
        
    });

    groupItem.SettingsItems.ShowCaption = DefaultBoolean.True;
    //groupItem.SettingsItemCaptions.Location = LayoutItemCaptionLocation.Top;
    groupItem.ParentContainerStyle.Paddings.Padding = Unit.Pixel(0);

    groupItem.ColCount = 4;
    groupItem.ColSpan = 4;

     
    groupItem.Items.Add(m =>
    {
        m.FieldName = "HoTen";
        m.ColSpan = 2; 
        m.SetNestedContent(() =>
        {
            Html.DevExpress().TextBoxFor(i => i.HoTen, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100); 
            }).Render();
        });
    });
    groupItem.Items.Add(m =>
     {
         m.FieldName = "GioiTinh";
         m.ColSpan = 1;
         //m.CaptionStyle.Font.Bold = true; 
         m.SetNestedContent(() =>
             {
                 Html.DevExpress().RadioButtonListFor(i => i.Gioitinh, mySettings =>
                 {
                     mySettings.Width = Unit.Percentage(100);
                     mySettings.Properties.ValueType = typeof(bool);
                     mySettings.Properties.RepeatLayout = RepeatLayout.Flow;
                     mySettings.Properties.RepeatDirection = RepeatDirection.Horizontal;
                     mySettings.Properties.RepeatColumns = 2;
                     mySettings.Properties.Items.Add("Nam", true);
                     mySettings.Properties.Items.Add("Nữ", false);
                 }).Render();
             });
     });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "Tuoi";
        m.ColSpan = 1; 
        m.SetNestedContent(() =>
        {
            Html.DevExpress().SpinEditFor(i => i.Tuoi, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100);
            }).Render();
        });
    });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "Sodienthoai";
        m.ColSpan = 1;
        //m.CaptionStyle.Font.Bold = true;
        m.SetNestedContent(() =>
        {
            Html.DevExpress().SpinEditFor(i => i.Sodienthoai, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100);
            }).Render();
        });
    });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "SoCMND";
        m.ColSpan = 1;
        //m.CaptionStyle.Font.Bold = true;
        m.SetNestedContent(() =>
        {
            Html.DevExpress().SpinEditFor(i => i.SoCMND, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100);
            }).Render();
        });
    });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "BHYT";
        m.ColSpan = 2;
        //m.CaptionStyle.Font.Bold = true;
        m.SetNestedContent(() =>
        {
            Html.DevExpress().MemoFor(i => i.BHYT, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100);
            }).Render();
        });
    });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "Diachi";
        m.ColSpan = 1;
        //m.CaptionStyle.Font.Bold = true;
        m.SetNestedContent(() =>
        {
            Html.DevExpress().MemoFor(i => i.Diachi, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100);
            }).Render();
        });
    });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "MA_TINH";
        m.ShowCaption = DefaultBoolean.False;
        m.ColSpan = 1;
        m.SetNestedContent(() =>
        {
            Html.RenderPartial("_ComboBoxTinh");
        });
    });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "MA_HUYEN";
        m.ShowCaption = DefaultBoolean.False;
        m.ColSpan = 1;
        m.SetNestedContent(() =>
        {
            Html.RenderPartial("_ComboBoxHuyen");
        });
    });
    groupItem.Items.Add(m =>
    {
        m.FieldName = "MA_XA";
        m.ColSpan = 1;
        m.SetNestedContent(() =>
        {
            Html.RenderAction("ComboBoxXaList","BenhNhan");
        });
    }); 
    groupItem.Items.Add(m =>
    {
        m.FieldName = "NgheNghiep";
        m.ColSpan = 4;
        //m.CaptionStyle.Font.Bold = true;
        m.SetNestedContent(() =>
        {
            Html.DevExpress().MemoFor(i => i.NgheNghiep, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100);
            }).Render();
        });
    }); 

    groupItem.Items.Add(m =>
      {
          m.FieldName = "MaNoiGioiThieu";
          m.Caption = "Nơi giới thiệu";
          m.ColSpan = 1;
          //m.CaptionStyle.Font.Bold = true;
          m.NestedExtensionSettings.Width = Unit.Percentage(100);
      }).SetNestedContent(() =>
      {
          Html.DevExpress().ComboBoxFor(i => i.MaNoiGioiThieu, cbSettings =>
          {
              cbSettings.Properties.DropDownStyle = DropDownStyle.DropDownList;
              cbSettings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
              cbSettings.Properties.Items.Add("Thuộc hệ thống CTCL", 1);
              cbSettings.Properties.Items.Add("Y tế công tham gia CTCL", 2);
              cbSettings.Properties.Items.Add("Y tế tư", 3);
              cbSettings.Properties.Items.Add("Cộng đồng", 4);
              cbSettings.Properties.Items.Add("Tự đến", 5);
              cbSettings.Width = Unit.Percentage(100);
              cbSettings.Properties.Width = Unit.Percentage(100);
          }).Render();
      }); 
    groupItem.Items.Add(m =>
    {
        m.FieldName = "NoiGioiThieu";
        m.ShowCaption =  DefaultBoolean.False;
        m.ColSpan =3;
        //m.CaptionStyle.Font.Bold = true;
        m.SetNestedContent(() =>
        {
            Html.DevExpress().MemoFor(i => i.NoiGioiThieu, mySettings =>
            {
                mySettings.Width = Unit.Percentage(100);
            }).Render();
        });
    });
     
    
    Session["ID_BenhNhan"] = Model != null ? Model.ID_BenhNhan + "" : "";
    Session["HoTen"] = Model != null ? Model.HoTen + "" : "";
    Session["Gioitinh"] = Model != null ? Model.Gioitinh == true ? "Nam" : "Nữ" : "";
    Session["Tuoi"] = Model != null ? Model.Tuoi + "" : "";
    Session["Diachi"] = Model != null ? Model.Diachi + "" : "";
    Session["MATINH"] = Model != null ? Model.MA_TINH + "" : "";
    Session["MAHUYEN"] = Model != null ? Model.MA_HUYEN + "" : "";

}).GetHtml()

NTP_MVC/Views/SoDieuTri/_MaBNQLPartial.cshtml
@Html.DevExpress().ComboBox(settings =>
{
    settings.Name = "MaBNQLComboBox";
    settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
    settings.Properties.DropDownStyle = DropDownStyle.DropDown;
    settings.Properties.DropDownHeight = 350;
    settings.CallbackRouteValues = new { Controller = "BenhNhan", Action = "MaBNQLPartial" };
    settings.Properties.CallbackPageSize = 50;
    settings.Properties.ValueField = "MaBNQL";
    settings.Properties.FilterMinLength = 4;
    settings.Properties.TextFormatString = "{0}";
    settings.Properties.ValueType = typeof(string); 
    settings.Properties.ClientSideEvents.BeginCallback = "function(s, e) {  e.customArgs['MaBNQLComboBox'] = MaBNQLComboBox.GetValue(); }";

    settings.Properties.Columns.Add("MaBNQL", "Mã Bệnh Nhân", 120);
    settings.Properties.Columns.Add("HoTen", "Họ và Tên", 130);
    settings.Properties.Columns.Add("GioiTinh", "Giới Tính", 60);
    settings.Properties.Columns.Add("Tuoi", "Tuổi", 40);
    settings.Properties.Columns.Add("TenTinh", "Tỉnh", 100);
    settings.Properties.Columns.Add("TenHuyen", "Huyện", 250);
    
}).BindList(ViewData["MaBNQL"]).GetHtml()