NTP_MVC/Models/BC_KetQuaDT.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_KetQuaDT
    {
        public int ID_BCKetQuaDT { get; set; }
        public byte Quy { get; set; }
        public int Nam { get; set; }
        public string DVBaocao { get; set; }
        public string MA_TINH { get; set; }
        public string MA_HUYEN { get; set; }
        public string NguoiBC { get; set; }
        public Nullable<System.DateTime> NgayBC { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public Nullable<int> NGUOI_NM { get; set; }
        public Nullable<bool> HuyenXN { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public Nullable<bool> PTNhap { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<System.DateTime> Ngayhuy { get; set; }
    }
}

NTP_MVC/Controllers/BCKetQuaDTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using NTP_MVC.Models;
using System.Data.Entity;

namespace NTP_MVC.Controllers
{
    public class BCKetQuaDTController : Controller
    {
        // GET: BC_KetQuaDT
        public ActionResult Index()
        {
            //Session["MATINH"] = "07";
            //Session["MAHUYEN"] = "0703";
            var MaTinh = Session["MATINH"] + "";
            if (MaTinh != "")
            {
                var MaHuyen = Session["MAHUYEN"] + "";
                ViewData["Tinhs"] = db.DM_Tinh.Where(t => t.MA_TINH.Equals(MaTinh)).ToList();
                if (MaHuyen == "")
                {
                    List<DM_Huyen> ListHuyen = new List<DM_Huyen>();
                    DM_Huyen h = new DM_Huyen() { TEN_HUYEN = "-- Tất cả--", MA_HUYEN = "0", MA_TINH = MaTinh };
                    ListHuyen.Add(h);
                    ListHuyen.AddRange(db.DM_Huyen.Where(m => m.MA_TINH.Equals(MaTinh)).ToList());
                    ViewData["Huyens"] = ListHuyen;
                }
                else
                {
                    ViewData["Huyens"] = db.DM_Huyen.Where(b => b.MA_HUYEN.Equals(MaHuyen)).ToList();
                }
                GetListBCKetQuaDT();

                BCDieuTriModel model = new BCDieuTriModel();
                model.BC_KQDieuTriBNLao = ViewData["ListBCKetQuaDT"] as List<BC_KetQuaDT>;

                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        NTP_DBEntities db = new NTP_DBEntities();
        #region GridBCKetQuaDT
        [HttpPost, ValidateInput(false)]
        public ActionResult BC_TNBNLAddNew(BC_KetQuaDT item)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int MaQuy = Request.Params["MaQuy"] != null ? Convert.ToInt16(Request.Params["MaQuy"]) : 0;
                    int Nam = Request.Params["Nam"] != null ? Convert.ToInt32((Request.Params["Nam"] + "").TrimStart('"').TrimEnd('"')) : 0;
                    if (MaQuy == 0) MaQuy = 1;

                    item.MA_TINH = Session["MATINH"] + "";
                    item.Quy = (byte)MaQuy;
                    item.Nam = Nam;
                    db.BC_KetQuaDT.Add(item);
                    db.SaveChanges();

                    for (int i = 0; i < 6; i++)
                    {
                        BC_KetQuaDT1 subitem = new BC_KetQuaDT1();
                        subitem.ID_BCKetQuaDT = item.ID_BCKetQuaDT;
                        // subitem.Phanloai = i;
                        db.BC_KetQuaDT1.Add(subitem);
                    }

                    for (int i = 0; i < 2; i++)
                    {
                        BC_KetQuaDT1 subitem = new BC_KetQuaDT1();
                        subitem.ID_BCKetQuaDT = item.ID_BCKetQuaDT;
                        //subitem.Phanloai = i;
                        db.BC_KetQuaDT1.Add(subitem);
                    }

                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return GridBCKetQuaDT();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult BC_TNBNLUpdate(BC_KetQuaDT item)
        {
            var model = db.BC_KetQuaDT;
            if (ModelState.IsValid)
            {
                try
                {
                    var modelItem = model.FirstOrDefault(it => it.ID_BCKetQuaDT == item.ID_BCKetQuaDT);
                    if (modelItem != null)
                    {
                        UpdateModel(modelItem);
                        db.SaveChanges();
                    }

                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return GridBCKetQuaDT();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Update3Grid(int ID_BCKetQuaDT)
        {
            try
            {

                for (int i = 0; i < 6; i++)
                {
                    var BC1 = db.BC_KetQuaDT1.Any(a => a.ID_BCKetQuaDT == ID_BCKetQuaDT);
                    if (BC1 == false)
                    {
                        BC_KetQuaDT1 subitem = new BC_KetQuaDT1();
                        subitem.ID_BCKetQuaDT = ID_BCKetQuaDT;
                        //subitem.Phanloai = i;
                        db.BC_KetQuaDT1.Add(subitem);
                    }
                }

                for (int i = 0; i < 2; i++)
                {
                    var BC2 = db.BC_KetQuaDT1.Any(a => a.ID_BCKetQuaDT == ID_BCKetQuaDT);
                    if (BC2 == false)
                    {
                        BC_KetQuaDT1 subitem = new BC_KetQuaDT1();
                        subitem.ID_BCKetQuaDT = ID_BCKetQuaDT;
                        //subitem.Phanloai = i;
                        db.BC_KetQuaDT1.Add(subitem);
                    }
                }
                db.SaveChanges();
            }
            catch (Exception e)
            {
                ViewData["EditError"] = e.Message;
            }
            return null;
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult BC_TNBNLDelete(string ID_BCKetQuaDT)
        {
            return null;
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult BC_TNBNLDelete(int ID_BCKetQuaDT)
        {
            if (ID_BCKetQuaDT != 0)
            {
                try
                {

                    foreach (var item1 in db.BC_KetQuaDT1.Where(a => a.ID_BCKetQuaDT.Equals(ID_BCKetQuaDT)))
                        db.BC_KetQuaDT1.Remove(item1);

                    var item = db.BC_KetQuaDT.FirstOrDefault(it => it.ID_BCKetQuaDT == ID_BCKetQuaDT);
                    if (item != null)
                        db.BC_KetQuaDT.Remove(item);
                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            return GridBCKetQuaDT();
        }


        [ValidateInput(false)]
        public ActionResult GridBCKetQuaDT()
        {
            GetListBCKetQuaDT();
            BCDieuTriModel model = new BCDieuTriModel();
            var MaTinh = Session["MATINH"] + "";
            List<DM_Huyen> ListHuyen = new List<DM_Huyen>();
            DM_Huyen h = new DM_Huyen() { TEN_HUYEN = "", MA_HUYEN = "", MA_TINH = MaTinh };
            ListHuyen.Add(h);
            ListHuyen.AddRange(db.DM_Huyen.Where(m => m.MA_TINH.Equals(MaTinh)).ToList());
            ViewData["Huyens"] = ListHuyen;
            model.ListHuyen = ViewData["Huyens"] as List<DM_Huyen>;
            model.BC_KQDieuTriBNLao = ViewData["ListBCKetQuaDT"] as List<BC_KetQuaDT>;

            return PartialView("GridBCKetQuaDT", model);
        }

        private void GetListBCKetQuaDT()
        {
            string matinh = Session["MATINH"] + "";

            int MaQuy = Request.Params["MaQuy"] != null ? Convert.ToInt16(Request.Params["MaQuy"]) : 1;
            int Nam = Request.Params["Nam"] != null ? Convert.ToInt32((Request.Params["Nam"] + "").TrimStart('"').TrimEnd('"')) : DateTime.Now.Year;
            
            ViewData["ListBCKetQuaDT"] = (from d in db.BC_KetQuaDT
                                          where d.MA_TINH.Equals(matinh)
                                              && d.Quy == MaQuy
                                              && d.Nam == Nam
                                          select d).ToList();
        }
        #endregion


        #region GridBCTN1
        /*--------------------GridBCTN1----------------------*/
        public ActionResult GridBCTN1()
        {
            if (Request.Params["ID_BCKetQuaDT"] != null)
            {
                var ID_BCKetQuaDT = Convert.ToInt32(Request.Params["ID_BCKetQuaDT"]);

                ViewData["ListBCKetQuaDT1"] = (from d in db.BC_KetQuaDT1
                                               where d.ID_BCKetQuaDT == ID_BCKetQuaDT
                                               select d).ToList();

            }
            return PartialView("GridBCTN1");
        }

        [ValidateInput(false)]
        public ActionResult GridBCTN1BatchEditingUpdateModel(MVCxGridViewBatchUpdateValues<BC_KetQuaDT1, int> updateValues)
        {
            foreach (var item in updateValues.Update)
            {
                if (updateValues.IsValid(item))
                    UpdateBCKetQuaDT1(item, updateValues);
            }
            return GridBCTN1();
        }
        protected void UpdateBCKetQuaDT1(BC_KetQuaDT1 item, MVCxGridViewBatchUpdateValues<BC_KetQuaDT1, int> updateValues)
        {
            try
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception e)
            {
                updateValues.SetErrorText(item, e.Message);
            }
        }
        /*-------------------------------------------------------------------*/

        #endregion


        #region GridBCTN2
        /*--------------------GridBCTN2----------------------*/
        public ActionResult GridBCTN2()
        {
            if (Request.Params["ID_BCKetQuaDT"] != null)
            {
                var ID_BCKetQuaDT = Convert.ToInt32(Request.Params["ID_BCKetQuaDT"]);

                ViewData["ListBCKetQuaDT2"] = (from d in db.BC_KetQuaDT1
                                               where d.ID_BCKetQuaDT == ID_BCKetQuaDT

NTP_MVC/Views/BCKetQuaDT/EditBCKQDT.cshtml
@Html.DevExpress().FormLayout(settings =>
        {
            settings.Name = "EditBCKetQuaDT";
            settings.RequiredMarkDisplayMode = RequiredMarkMode.None;
            settings.Width = Unit.Percentage(100);


            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 1: Kết quả điều trị (toàn bộ bệnh nhân, trừ bệnh nhân chuyển đến)";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {

                    Html.RenderPartial("GridBCKetQuaDT1");
                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 2: Kết quả điều trị bệnh lao trẻ em (<15 tuổi)";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCKetQuaDT2");

                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 3 : Kết quả điều trị BN Lao/HIV";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCKetQuaDT3");

                });
            });

            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 4: Báo cáo hoạt động phối hợp lao/HIV (cùng quý với số liệu phân tích ở Phần 1)";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCKetQuaDT4");

                });
            });


            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 5: Kết quả điều trị  (lô bệnh nhân do y tế công tham gia CTCL giám sát, hỗ trợ điều trị)";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCKetQuaDT5");

                });
            });


            settings.Items.AddGroupItem(group =>
            {
                group.Caption = "Phần 6: Kết quả điều trị  (lô bệnh nhân do y tế tư giám sát, hỗ trợ điều trị)";
                group.ShowCaption = DefaultBoolean.True;
                group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
                group.Width = Unit.Percentage(100);
                group.Items.Add(m =>
                {
                    m.ShowCaption = DefaultBoolean.False;
                    m.RequiredMarkDisplayMode = FieldRequiredMarkMode.Hidden;
                }).SetNestedContent(() =>
                {
                    Html.RenderPartial("GridBCKetQuaDT6");

                });
            });

             
        }).GetHtml()

NTP_MVC/Views/BCKetQuaDT/Index.cshtml
<script>
    var ID_BCKetQuaDT = "";
    var ID_BCKetQuaDTCD = "";

    function OnGridBCKetQuaDTFocusedRowChanged(s, e) {
        if (s.GetFocusedRowIndex() != -1) {
            ID_BCKetQuaDT = s.GetRowKey(s.GetFocusedRowIndex());
            update3Grid();
            GridBCTN1.PerformCallback();
            GridBCTN2.PerformCallback();
            GridBCTN3.PerformCallback();
        }
    }

    function update3Grid() {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Update3Grid", "BCKetQuaDT")',
            data: { ID_BCKetQuaDT: ID_BCKetQuaDT }
        });
    }

    function GridBCKetQuaDT_OnBeginCallback(s, e) {
        e.customArgs["ID_BCKetQuaDT"] = ID_BCKetQuaDT;
    }

    function OnGridBCKetQuaDTRowDblClick(s, e) {
        GridBCKetQuaDT.StartEditRow(GridBCKetQuaDT.GetFocusedRowIndex());
    }
    $(function () {
        GridBCKetQuaDT.PerformCallback();
    });

    function OnGridBNFocusedRowChanged(s, e) {
        ID_BCKetQuaDT = s.GetRowKey(s.GetFocusedRowIndex());
    }
    function OnGridBNCDFocusedRowChanged(s, e) {
        ID_BCKetQuaDTCD = s.GetRowKey(s.GetFocusedRowIndex());
    }

    var currentColumnName;
    function OnBatchEditStartEditing(s, e) {
        currentColumnName = e.focusedColumn.fieldName;
    }
    function OnBatchEditEndEditing(s, e) {
        window.setTimeout(function () {
            var a1 = s.batchEditApi.GetCellValue(e.visibleIndex, "Moi");
            var a2 = s.batchEditApi.GetCellValue(e.visibleIndex, "Taiphat");
            var a3 = s.batchEditApi.GetCellValue(e.visibleIndex, "Thatbai");
            var a4 = s.batchEditApi.GetCellValue(e.visibleIndex, "Taitri");
            var a5 = s.batchEditApi.GetCellValue(e.visibleIndex, "AFBKhac");
            var a6 = s.batchEditApi.GetCellValue(e.visibleIndex, "AmNho");
            var a7 = s.batchEditApi.GetCellValue(e.visibleIndex, "AmTrung");
            var a8 = s.batchEditApi.GetCellValue(e.visibleIndex, "AmLon");
            var a9 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiPhoiNho");
            var a10 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiPhoiTrung");
            var a11 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiPhoiLon");
            var a12 = s.batchEditApi.GetCellValue(e.visibleIndex, "NgoaiphoiKhac");
            s.batchEditApi.SetCellValue(e.visibleIndex, "TongCong", a1 + a2 + a3 + a4 + a5 + a6 + a7 + a8 + a9 + a10 + a11 + a12);
        }, 10);
    }

</script>
@Html.DevExpress().FormLayout(settings =>
{
    settings.Name = "ListBCKetQuaDT";
    settings.RequiredMarkDisplayMode = RequiredMarkMode.None;
    settings.Width = Unit.Percentage(100);
    settings.ColCount = 1;
    settings.Items.AddGroupItem(group =>
    {
        group.Caption = "Danh sách báo cáo tình hình thu nhận bệnh nhân lao";
        group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
        group.Width = Unit.Percentage(100);
        group.Items.Add(item =>
        {
            item.Caption = "Thuộc đơn vị";
            item.ShowCaption = DefaultBoolean.False;
            item.SetNestedContent(() =>
            {
                ViewContext.Writer.Write("<table><tr><td style=\"padding-right:5px;\">");
                Html.RenderPartial("_ComboBoxTinh");
                ViewContext.Writer.Write("</td><td style='padding-left:30px;padding-right:5px;'>");
                Html.DevExpress().ComboBox(mySettings =>
                {
                    mySettings.Name = "cboQuy";
                    mySettings.Properties.Caption = "Năm BC";
                    mySettings.Width = Unit.Pixel(100);
                    mySettings.Properties.Items.Add("Quý I", 1);
                    mySettings.Properties.Items.Add("Quý II", 2);
                    mySettings.Properties.Items.Add("Quý III", 3);
                    mySettings.Properties.Items.Add("Quý IV", 4);
                    mySettings.Properties.DropDownRows = 5;
                    mySettings.SelectedIndex = 0;
                }).Render();

                ViewContext.Writer.Write("</td><td style='padding-right:5px;'>");
                Html.DevExpress().TextBox(mySettings =>
                {
                    mySettings.Name = "txtNam";
                    mySettings.Properties.Caption = "";
                    mySettings.Properties.CaptionSettings.ShowColon = false;
                    mySettings.Width = Unit.Pixel(60);
                }).Bind(DateTime.Now.Year + "" ?? "").Render();
                ViewContext.Writer.Write("</td><td style='padding-left:20px;padding-right:5px;'>");
                Html.DevExpress().Button(
                            MyButton =>
                            {
                                MyButton.Name = "btnSearch";
                                MyButton.Width = 90;
                                MyButton.Text = "Xem";
                                MyButton.ClientSideEvents.Click = "function() { GridBCKetQuaDT.PerformCallback(); }";
                                MyButton.Images.Image.Url = "~/Content/Images/blue_search.png";
                                MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                            }).Render();
                ViewContext.Writer.Write("</td></tr></table>");
            });
        });
    });
}).GetHtml()

@using (Html.BeginForm())
{

    Html.DevExpress().Panel(settings5 =>
    {
        settings5.Name = "Panel";
        settings5.FixedPosition = PanelFixedPosition.None;
        settings5.SettingsCollapsing.ExpandEffect = PanelExpandEffect.Auto;
        settings5.SetContent(() =>
        {
            Html.DevExpress().Button(
               MyButton =>
               {
                   MyButton.Name = "btnThemMoiBC";
                   MyButton.Width = 90;
                   MyButton.Text = "Thêm mới";
                   MyButton.ClientSideEvents.Click = "function() { GridBCKetQuaDT.AddNewRow();}";
                   MyButton.Images.Image.Url = "~/Content/Images/add.png";
                   MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
               }).Render();
            Html.DevExpress().Button(
                    MyButton =>
                    {
                        MyButton.Name = "btnSuaBC";
                        MyButton.Width = 90;
                        MyButton.Text = "Sửa";
                        MyButton.Images.Image.Url = "~/Content/Images/edit.png";
                        MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                        MyButton.ClientSideEvents.Click = "function() { GridBCKetQuaDT.StartEditRow(GridBCKetQuaDT.GetFocusedRowIndex());}";

                    }).Render();
            Html.DevExpress().Button(
                               myButton =>
                               {
                                   myButton.Name = "btnLuuBC";
                                   myButton.Text = "Lưu";
                                   myButton.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
                                   myButton.Images.Image.Url = "~/Content/Images/save.png";
                                   myButton.ClientSideEvents.Click = "function( ) { GridBCKetQuaDT.UpdateEdit();   GridBCTN1.PerformCallback();}";
                                   myButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                               }).GetHtml();
            Html.DevExpress().Button(
                  myButton =>
                  {
                      myButton.Name = "btnHuyBC";
                      myButton.Text = "Hủy";
                      myButton.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
                      myButton.Images.Image.Url = "~/Content/Images/cancel.png";
                      myButton.ClientSideEvents.Click = "function( ) { GridBCKetQuaDT.CancelEdit();  }";
                      myButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                  }).GetHtml();
            Html.DevExpress().Button(
                    MyButton =>
                    {
                        MyButton.Name = "btnXoa";
                        MyButton.Width = 90;
                        MyButton.Text = "Xóa";
                        MyButton.Images.Image.Url = "~/Content/Images/delete.png";
                        MyButton.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                        MyButton.ClientSideEvents.Click = "function( ) { if(confirm('Bạn có muốn xóa toàn bộ Báo cáo đã nhập?'))  { GridBCKetQuaDT.DeleteRow(); } }";
                    }).Render();
        });
    }).GetHtml();


    Html.DevExpress().Splitter(
        settings =>
        {
            settings.Name = "splResizing";
            settings.Height = 2000;
            settings.Width = Unit.Percentage(100);
            settings.Styles.Pane.Paddings.Padding = 0;

            settings.Panes.Add(listBoxPane =>
            {
                listBoxPane.Name = "listBoxContainer";
                listBoxPane.Size = Unit.Percentage(20);
                listBoxPane.MinSize = 250;
                listBoxPane.ShowCollapseBackwardButton = DefaultBoolean.True;
                listBoxPane.SetContent(() =>
                {
                    Html.RenderPartial("GridBCKetQuaDT");
                });
            });
            settings.Panes.Add(contentPane =>
            {
                contentPane.MinSize = 250;
                contentPane.Panes.Add(gridPane =>
                {
                    gridPane.Name = "gridContainer";
                    gridPane.Size = Unit.Percentage(60);
                    gridPane.MinSize = 100;
                    gridPane.SetContent(() =>
                    {
                        Html.RenderPartial("EditBCKQDT");
                    });
                });
            });

            // settings.ClientSideEvents.PaneResized = "OnSplitterPaneResized";
        }).GetHtml();
}

NTP_MVC/Views/BCKetQuaDT/_ComboBoxHuyen.cshtml
@Html.DevExpress().ComboBox(settings =>
{
    settings.Name = "ComboBoxHuyen";
    settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
    settings.Properties.DropDownStyle = DropDownStyle.DropDown; 
    settings.Properties.CallbackPageSize = 5000;
    settings.Properties.ValueField = "MA_HUYEN";
    settings.Properties.TextField = "TEN_HUYEN";
    settings.Properties.ValueType = typeof(string);
    settings.Properties.Caption = "Huyện"; 
    settings.SelectedIndex = 0;
    settings.ClientEnabled = Session["MAHUYEN"] == null;
}).BindList(ViewData["Huyens"]).GetHtml()

NTP_MVC/Views/BCKetQuaDT/_ComboBoxTinh.cshtml
@Html.DevExpress().ComboBox(settings =>
{
    settings.Name = "ComboBoxTinh";
    settings.Properties.IncrementalFilteringMode = IncrementalFilteringMode.Contains;
    settings.CallbackRouteValues = new { Controller = "BenhNhan", Action = "ComboBoxTinhList" };
    settings.Properties.DropDownStyle = DropDownStyle.DropDown;
    settings.Properties.ValueType = typeof(string);
    settings.Properties.ValueField = "MA_TINH";
    settings.Properties.TextField = "TEN_TINH";
    settings.Properties.Caption = "Tỉnh";
    settings.Properties.ClientSideEvents.SelectedIndexChanged = "function(s, e) {ComboBoxHuyen.PerformCallback(); }";
    settings.SelectedIndex = 0;
    settings.ClientEnabled = Session["MATINH"] == "";
}).BindList(ViewData["Tinhs"]).GetHtml()